---
abstract: 'fetch source tarballs from CPAN'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires: {}
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-sourcepan
provides:
  App::sourcepan:
    file: lib/App/sourcepan.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
